name: sec-auto
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli-python=1.1.0=py312hde4cb15_2
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - cachecontrol=0.14.2=pyha770c72_0
  - cachecontrol-with-filecache=0.14.2=pyhd8ed1ab_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py312h0fad829_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-lock=3.0.0=pyh534df25_0
  - crashtest=0.4.1=pyhd8ed1ab_1
  - distlib=0.3.9=pyhd8ed1ab_1
  - dulwich=0.22.8=py312hcd83bfe_0
  - ensureconda=1.4.7=pyh29332c3_0
  - expat=2.7.0=h286801f_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.1.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - keyring=25.6.0=pyh534df25_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.2=ha82da77_0
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libopenblas=0.3.29=openmp_hf332438_0
  - libsqlite=3.45.2=h091b4b1_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.2=hdb05f8b_1
  - markupsafe=3.0.2=py312h998013c_1
  - more-itertools=10.6.0=pyhd8ed1ab_0
  - msgpack-python=1.1.0=py312h6142ec9_0
  - ncurses=6.4=h313beb8_0
  - numpy=2.2.4=py312h7c1f314_0
  - openssl=3.5.0=h81ee809_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hcb1e3ce_3
  - pip=25.0=py312hca03da5_0
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - platformdirs=4.3.7=pyh29332c3_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-core=2.33.1=py312hd60eec9_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.2=hdf0ec26_0_cpython
  - python-build=1.2.2.post1=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-installer=0.7.0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h998013c_2
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=pyhd8ed1ab_1
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - ruamel.yaml=0.18.10=py312hea69d52_0
  - ruamel.yaml.clib=0.2.8=py312h0bf5046_1
  - semver=3.0.4=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlite=3.45.2=hf2abe2d_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomlkit=0.13.2=pyha770c72_1
  - trove-classifiers=2025.4.11.15=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - virtualenv=20.30.0=pyhd8ed1ab_0
  - wheel=0.45.1=py312hca03da5_0
  - xattr=1.1.0=py312h024a12e_1
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py312hea69d52_1
  - pip:
      - astroid==3.3.9
      - autopage==0.5.2
      - bandit==1.8.3
      - bcrypt==4.3.0
      - black==25.1.0
      - cliff==4.9.1
      - cmd2==2.5.11
      - contourpy==1.3.1
      - cryptography==44.0.2
      - cycler==0.12.1
      - debtcollector==3.0.0
      - decorator==5.2.1
      - dill==0.3.9
      - dogpile-cache==1.3.4
      - dotenv==0.9.9
      - flake8==7.2.0
      - fonttools==4.57.0
      - gnureadline==8.2.13
      - iniconfig==2.1.0
      - iso8601==2.1.0
      - isort==6.0.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - keystoneauth1==5.10.0
      - kiwisolver==1.4.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mypy-extensions==1.0.0
      - netaddr==1.3.0
      - openstacksdk==4.5.0
      - os-service-types==1.7.0
      - osc-lib==4.0.0
      - oslo-config==9.7.1
      - oslo-i18n==6.5.1
      - oslo-serialization==5.7.0
      - oslo-utils==8.2.0
      - package-name==0.1
      - paramiko==3.5.1
      - pathspec==0.12.1
      - pbr==6.1.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - pluggy==1.5.0
      - prettytable==3.16.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pycodestyle==2.13.0
      - pyflakes==3.3.2
      - pygments==2.19.1
      - pylint==3.3.6
      - pynacl==1.5.0
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pytest==8.3.5
      - python-cinderclient==9.7.0
      - python-dotenv==1.1.0
      - python-keystoneclient==5.6.0
      - python-nmap==0.7.1
      - python-openstackclient==8.0.0
      - requestsexceptions==1.4.0
      - rfc3986==2.0.0
      - rich==14.0.0
      - scapy==2.6.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - setuptools==78.1.0
      - stevedore==5.4.1
      - threadpoolctl==3.6.0
      - virtualenv-clone==0.5.7
      - virtualenvwrapper==6.1.1
      - wcwidth==0.2.13
      - wrapt==1.17.2
      - yara-python==4.5.1
prefix: /Users/zephrinemathew/anaconda3/envs/sec-auto
